# build environment
FROM node:lts-alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

ARG REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
ENV REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}

ARG REACT_APP_EMAILJS_SERVICEID=${REACT_APP_EMAILJS_SERVICEID}
ENV REACT_APP_EMAILJS_SERVICEID=${REACT_APP_EMAILJS_SERVICEID}

ARG REACT_APP_EMAILJS_TEMPLATEID=${REACT_APP_EMAILJS_TEMPLATEID}
ENV REACT_APP_EMAILJS_TEMPLATEID=${REACT_APP_EMAILJS_TEMPLATEID}

ARG REACT_APP_EMAILJS_KEYID=${REACT_APP_EMAILJS_KEYID}
ENV REACT_APP_EMAILJS_KEYID=${REACT_APP_EMAILJS_KEYID}

ARG REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}
ENV REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}

COPY . /usr/src/app
RUN npm install
RUN npm run build

# production environment
FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
RUN mkdir -p /etc/nginx/conf.d
COPY ./default.conf /etc/nginx/conf.d/
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]